catalog_name: hive_metastore
schema_name: louisreinaldo
table_prefix: life_expectancy

parameters:
  learning_rate: 0.01
  n_estimators: 100
  max_depth: 10

num_features:
  - Adult_Mortality
  - infant_deaths
  - Alcohol
  - percentage_expenditure
  - Hepatitis_B
  - Measles
  - BMI
  - under-five_deaths
  - Polio
  - Total_expenditure
  - Diphtheria
  - HIV_AIDS
  - GDP
  - Population
  - thinness_1-19_years
  - thinness_5-9_years
  - Income_composition_of_resources
  - Schooling

cat_features:
  - Status

target: Life_expectancy
